### ISSUE TITLE
add previews for puzzle types

### ISSUE THREAD

**Issue by robx** [robx/pzprnode#12]
pzprxs adds previews etc for the puzzle editor, instead of just the completed puzzles; we should add the same to pzprnode, compare https://github.com/robx/pzprjs/pull/271#issuecomment-1304555640

e.g.
```
<meta name="description" content="Create a Anglers puzzle.">
<meta property="og:title" content="Anglers">
<meta property="og:description" content="Create a Anglers puzzle.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://pzprxs.vercel.app/p?anglers">
<meta property="og:image" content="https://pzprxs.vercel.app/pv?frame=5&anglers">
<meta property="og:locale" content="en_US">
<meta property="og:locale:alternate" content="ja_JP">
```

**Comment by x-sheep** [comment]
For reference, the source file used to create all preview data, which can be loaded as a savefile and rendered.

https://github.com/x-sheep/pzprjs/blob/e1991c4c92f9374f2bb1dd8ca44713e86726105c/src-api/build-saveicons.js

**Comment by robx** [comment]
This is done.
